github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Eclipse Tyrus]
description: [Java API for WebSocket reference implementation for easy development of WebSocket applications (JSR 356)]

links:
  source: https://github.com/eclipse-ee4j/tyrus
  #docs: documentation
  javadocs: docs/api/?overview-summary.html
  download: https://github.com/eclipse-ee4j/tyrus/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/tyrus-dev
  #faq: FAQ
